# Tesnores
---
Las redes neuronales son transformaciones de representaciones de numeros flotantes a otro tip de representacion de numeros flotantes. <br>
Estas representaciones de numeros flotantes son guardadas en Tensores. <br>
Los Tensores son Matrices **multidimensionales**.

<img src="img/redes_tensores.png">

In [41]:
import torch
a = torch.ones(3) 
a

tensor([1., 1., 1.])

In [42]:
#Distribución normal
torch.normal(2,3,(3,3))

tensor([[-0.0814,  2.2741,  1.1295],
        [ 1.3342,  1.7585,  5.9387],
        [-0.8565,  0.4561, -0.7343]])

In [43]:
#Syntax estilo numpy
a[1] = 60
a

tensor([ 1., 60.,  1.])

<img src="img/2_1.png"/>

In [6]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0], 
                       [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [5]:
# 3 Filas, 2 Columnas
points.shape

torch.Size([3, 2])

## Tensores en Memoria

Los tensores se basan en:
- Storage 
- Stride
- Size
- Offset

<img src="img/2_2.png"/>

En las listas, cada elemento es como un objeto, en cambio en los tensroes todos los elementos estan como un único objeto.

In [46]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0], 
                       [2.0, 1.0]])
#Valores en Memoria
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

<img src="img/2_3.png"/>

In [49]:
points_storage = points.storage()
points_storage[0] = 39.0
points

tensor([[39.,  1.],
        [ 5.,  3.],
        [ 2.,  1.]])

El stride define cada cuantos "pasos" se cambia en una dimensión

In [12]:
points.stride()

(2, 1)

In [13]:
points.storage()

 2.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

Esto permite que varias operaciones tengan un coste computacional muy baja, porque solo se opera el mismo storage. 

In [51]:
#Sigue usando el mismo storage, solo cambia el stride
points_t = points.t()
points_t
id(points.storage()) == id(points_t.storage())

True

In [15]:
points.stride()

(2, 1)

In [16]:
points_t.stride()

(1, 2)

In [17]:
points.is_contiguous()

True

In [55]:
points_t.is_contiguous()

False

In [56]:
#transformar en contiguous
points_t.contiguous()

tensor([[39.,  5.,  2.],
        [ 1.,  3.,  1.]])

contiguous hace referencia a que el orden en memoria no es el mismo con el que se representa

## Types 
---
Al igual que numpy, los tensores son elementos del mismo tipo. <br>
Lista de Types: https://pytorch.org/docs/stable/tensors.html

In [19]:
# 1  Método
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [20]:
# 2 Método
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [21]:
# 3 Método
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [59]:
# Subselección igual que Numpy
points[1:]      
points[1:, :]   
points[1:, 0]   

tensor([5., 2.])

In [60]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

Podemos Elegir en que aparato hacer las operaciones

In [64]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="cpu")
#points_gpu = points.to(device='cuda')
points_cpu = points_gpu.to(device='cpu')

<img src="img/dispatcher.png"/> 

### Ejemplo de Tensor en Memoria 

In [77]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0], 
                       [2.0, 1.0]])
#Valores en Memoria
print( points.storage())
#Stride
print( points.stride())

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]
(2, 1)


In [80]:
points_sub = points[:,1]
print(points_sub)
print(points_sub.storage())
print(points_sub.stride())
print(points_sub.storage_offset())

tensor([1., 3., 1.])
 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]
(2,)
1


## Serializando Tensores

No queremos reentrenar los modelos, por esto utilizamos métodos para guardar los parámetros (tensores):

- Torch con pickle
- HDF5

In [89]:
#Pickle
torch.save(points, "extras/puntos.t")

In [87]:
torch.load( "extras/puntos.t")

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [98]:
points2 = points.t

In [103]:
import h5py

f = h5py.File('extras/ourpoints2.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
dset2 = f.create_dataset("transp", data =points.numpy())
f.close()

In [137]:
f = h5py.File('extras/ourpoints2.hdf5', 'r')
x = f['coords']
y = f["transp"]
print(x)
mi_tesnor = torch.from_numpy(x[-len(x):])
f.close()

<HDF5 dataset "coords": shape (3, 2), type "<f4">
